name = "capsuletech"
main = "worker/index.js"
compatibility_date = "2025-12-19"
pages_build_output_dir = "ui/dist"

[vars]
RELAY_BASE = "https://capsuletech.onrender.com"

[[r2_buckets]]
binding = "ARTIFACTS_BUCKET"
bucket_name = "capsulebucket"
