"""Stable error codes for the BEF verifier API contract."""

OK = "OK"

# Parsing & Canonicalization
E001_UNSUPPORTED_ENCODING = "E001_UNSUPPORTED_ENCODING"
E002_PARSE_FAILED = "E002_PARSE_FAILED"
E003_SCHEMA_UNSUPPORTED = "E003_SCHEMA_UNSUPPORTED"
E004_CANONICALIZATION_FAILED = "E004_CANONICALIZATION_FAILED"

# Capsule Integrity
E010_CAPSULE_HASH_MISSING = "E010_CAPSULE_HASH_MISSING"
E011_CAPSULE_HASH_MISMATCH = "E011_CAPSULE_HASH_MISMATCH"
E012_CAPSULE_HEADER_MISSING = "E012_CAPSULE_HEADER_MISSING"
E013_CAPSULE_HEADER_MISMATCH = "E013_CAPSULE_HEADER_MISMATCH"

# Authorship / Impersonation
E020_SIGNATURE_MISSING = "E020_SIGNATURE_MISSING"
E021_SIGNATURE_INVALID = "E021_SIGNATURE_INVALID"
E022_SIGNER_NOT_AUTHORIZED = "E022_SIGNER_NOT_AUTHORIZED"

# Policy / Version Pinning
E030_POLICY_ID_MISSING = "E030_POLICY_ID_MISSING"
E031_POLICY_VERSION_MISSING = "E031_POLICY_VERSION_MISSING"
E032_POLICY_UNKNOWN = "E032_POLICY_UNKNOWN"
E033_POLICY_HASH_MISMATCH = "E033_POLICY_HASH_MISMATCH"
E034_POLICY_NOT_IN_REGISTRY = "E034_POLICY_NOT_IN_REGISTRY"
E036_POLICY_DOCUMENT_MISSING = "E036_POLICY_DOCUMENT_MISSING"

# Proof Artifact Binding
E050_PROOF_MISSING = "E050_PROOF_MISSING"
E051_PROOF_FORMAT_MISSING = "E051_PROOF_FORMAT_MISSING"
E052_PROOF_HASH_MISMATCH = "E052_PROOF_HASH_MISMATCH"
E053_PROOF_STATEMENT_MISMATCH = "E053_PROOF_STATEMENT_MISMATCH"
E054_PROOF_VERIFICATION_FAILED = "E054_PROOF_VERIFICATION_FAILED"
E055_NOVA_STATE_MISMATCH = "E055_NOVA_STATE_MISMATCH"

# Commitment / Index Integrity
E060_ROW_INDEX_COMMITMENT_MISSING = "E060_ROW_INDEX_COMMITMENT_MISSING"
E061_ROW_INDEX_COMMITMENT_INVALID_FORMAT = "E061_ROW_INDEX_COMMITMENT_INVALID_FORMAT"
E062_ROW_ARCHIVE_MISSING = "E062_ROW_ARCHIVE_MISSING"
E063_CHUNK_ROOTS_DIGEST_MISMATCH = "E063_CHUNK_ROOTS_DIGEST_MISMATCH"
E064_MERKLE_PROOF_INVALID = "E064_MERKLE_PROOF_INVALID"
E065_CHUNK_ROOT_MISMATCH = "E065_CHUNK_ROOT_MISMATCH"
E066_CHUNK_LENGTH_INVALID = "E066_CHUNK_LENGTH_INVALID"
E075_CHUNK_HANDLE_INVALID = "E075_CHUNK_HANDLE_INVALID"
E076_CHUNK_CARDINALITY_MISMATCH = "E076_CHUNK_CARDINALITY_MISMATCH"

# DA Audit
E070_DA_MODE_UNSUPPORTED = "E070_DA_MODE_UNSUPPORTED"
E071_DA_CHALLENGE_MISSING = "E071_DA_CHALLENGE_MISSING"
E072_DA_CHALLENGE_HASH_MISMATCH = "E072_DA_CHALLENGE_HASH_MISMATCH"
E073_DA_CHALLENGE_UNTRUSTED = "E073_DA_CHALLENGE_UNTRUSTED"
E074_AVAILABILITY_FAILED = "E074_AVAILABILITY_FAILED"
E077_DA_CHALLENGE_BINDING_INVALID = "E077_DA_CHALLENGE_BINDING_INVALID"

# Policy enforcement
E101_POLICY_VIOLATION_FORBID_GPU = "E101_POLICY_VIOLATION_FORBID_GPU"
E102_POLICY_MISSING_PUBLIC_OUTPUT = "E102_POLICY_MISSING_PUBLIC_OUTPUT"
E103_POLICY_TRACK_UNKNOWN = "E103_POLICY_TRACK_UNKNOWN"
E104_POLICY_MANIFEST_MISSING = "E104_POLICY_MANIFEST_MISSING"
E105_POLICY_DOCKER_DIGEST_MISSING = "E105_POLICY_DOCKER_DIGEST_MISSING"
E106_MANIFEST_SIGNATURE_MISSING = "E106_MANIFEST_SIGNATURE_MISSING"
E107_MANIFEST_SIGNATURE_INVALID = "E107_MANIFEST_SIGNATURE_INVALID"
E108_MANIFEST_SIGNER_UNTRUSTED = "E108_MANIFEST_SIGNER_UNTRUSTED"
E109_MANIFEST_REGISTRY_MISMATCH = "E109_MANIFEST_REGISTRY_MISMATCH"

# Event log binding
E201_EVENT_LOG_MISMATCH = "E201_EVENT_LOG_MISMATCH"

# Proof system / profile binding
E301_PROOF_SYSTEM_MISMATCH = "E301_PROOF_SYSTEM_MISMATCH"
E302_VERIFICATION_PROFILE_UNSATISFIED = "E302_VERIFICATION_PROFILE_UNSATISFIED"
