"""Stable exit codes for CI integration.

Exit codes are designed for deterministic behavior in CI pipelines:
- 0:  Verified successfully
- 10: Proof verification failed
- 11: Policy mismatch
- 12: Commitment or index verification failed
- 13: DA audit failed
- 14: Replay diverged
- 20: Malformed or parse error
"""
from __future__ import annotations

from bef_zk.verifier_errors import (
    OK,
    # Parse errors (E00x)
    E001_UNSUPPORTED_ENCODING,
    E002_PARSE_FAILED,
    E003_SCHEMA_UNSUPPORTED,
    E004_CANONICALIZATION_FAILED,
    # Capsule integrity (E01x)
    E010_CAPSULE_HASH_MISSING,
    E011_CAPSULE_HASH_MISMATCH,
    E012_CAPSULE_HEADER_MISSING,
    E013_CAPSULE_HEADER_MISMATCH,
    # Authorship (E02x)
    E020_SIGNATURE_MISSING,
    E021_SIGNATURE_INVALID,
    E022_SIGNER_NOT_AUTHORIZED,
    # Policy (E03x)
    E030_POLICY_ID_MISSING,
    E031_POLICY_VERSION_MISSING,
    E032_POLICY_UNKNOWN,
    E033_POLICY_HASH_MISMATCH,
    E034_POLICY_NOT_IN_REGISTRY,
    E036_POLICY_DOCUMENT_MISSING,
    # Proof binding (E05x)
    E050_PROOF_MISSING,
    E051_PROOF_FORMAT_MISSING,
    E052_PROOF_HASH_MISMATCH,
    E053_PROOF_STATEMENT_MISMATCH,
    E054_PROOF_VERIFICATION_FAILED,
    E055_NOVA_STATE_MISMATCH,
    # Commitment/Index (E06x)
    E060_ROW_INDEX_COMMITMENT_MISSING,
    E061_ROW_INDEX_COMMITMENT_INVALID_FORMAT,
    E062_ROW_ARCHIVE_MISSING,
    E063_CHUNK_ROOTS_DIGEST_MISMATCH,
    E064_MERKLE_PROOF_INVALID,
    E065_CHUNK_ROOT_MISMATCH,
    E066_CHUNK_LENGTH_INVALID,
    E075_CHUNK_HANDLE_INVALID,
    E076_CHUNK_CARDINALITY_MISMATCH,
    # DA Audit (E07x)
    E070_DA_MODE_UNSUPPORTED,
    E071_DA_CHALLENGE_MISSING,
    E072_DA_CHALLENGE_HASH_MISMATCH,
    E073_DA_CHALLENGE_UNTRUSTED,
    E074_AVAILABILITY_FAILED,
    # Policy Enforcement (E1xx)
    E101_POLICY_VIOLATION_FORBID_GPU,
    E102_POLICY_MISSING_PUBLIC_OUTPUT,
    E103_POLICY_TRACK_UNKNOWN,
    E104_POLICY_MANIFEST_MISSING,
    E105_POLICY_DOCKER_DIGEST_MISSING,
    E106_MANIFEST_SIGNATURE_MISSING,
    E107_MANIFEST_SIGNATURE_INVALID,
    E108_MANIFEST_SIGNER_UNTRUSTED,
    E109_MANIFEST_REGISTRY_MISMATCH,
    # Event log (E2xx)
    E201_EVENT_LOG_MISMATCH,
    # Proof system (E3xx)
    E301_PROOF_SYSTEM_MISMATCH,
    E302_VERIFICATION_PROFILE_UNSATISFIED,
)

# Exit code definitions
EXIT_VERIFIED = 0
EXIT_PROOF_INVALID = 10
EXIT_POLICY_MISMATCH = 11
EXIT_COMMITMENT_FAILED = 12
EXIT_DA_AUDIT_FAILED = 13
EXIT_REPLAY_DIVERGED = 14
EXIT_MALFORMED = 20

# Map error codes to exit codes
_ERROR_TO_EXIT: dict[str, int] = {
    OK: EXIT_VERIFIED,

    # Parse errors -> malformed
    E001_UNSUPPORTED_ENCODING: EXIT_MALFORMED,
    E002_PARSE_FAILED: EXIT_MALFORMED,
    E003_SCHEMA_UNSUPPORTED: EXIT_MALFORMED,
    E004_CANONICALIZATION_FAILED: EXIT_MALFORMED,

    # Capsule integrity -> malformed
    E010_CAPSULE_HASH_MISSING: EXIT_MALFORMED,
    E011_CAPSULE_HASH_MISMATCH: EXIT_MALFORMED,
    E012_CAPSULE_HEADER_MISSING: EXIT_MALFORMED,
    E013_CAPSULE_HEADER_MISMATCH: EXIT_MALFORMED,

    # Authorship -> malformed
    E020_SIGNATURE_MISSING: EXIT_MALFORMED,
    E021_SIGNATURE_INVALID: EXIT_MALFORMED,
    E022_SIGNER_NOT_AUTHORIZED: EXIT_MALFORMED,

    # Policy errors -> policy mismatch
    E030_POLICY_ID_MISSING: EXIT_POLICY_MISMATCH,
    E031_POLICY_VERSION_MISSING: EXIT_POLICY_MISMATCH,
    E032_POLICY_UNKNOWN: EXIT_POLICY_MISMATCH,
    E033_POLICY_HASH_MISMATCH: EXIT_POLICY_MISMATCH,
    E034_POLICY_NOT_IN_REGISTRY: EXIT_POLICY_MISMATCH,
    E036_POLICY_DOCUMENT_MISSING: EXIT_POLICY_MISMATCH,

    # Proof binding -> proof invalid
    E050_PROOF_MISSING: EXIT_PROOF_INVALID,
    E051_PROOF_FORMAT_MISSING: EXIT_PROOF_INVALID,
    E052_PROOF_HASH_MISMATCH: EXIT_PROOF_INVALID,
    E053_PROOF_STATEMENT_MISMATCH: EXIT_PROOF_INVALID,
    E054_PROOF_VERIFICATION_FAILED: EXIT_PROOF_INVALID,
    E055_NOVA_STATE_MISMATCH: EXIT_PROOF_INVALID,

    # Commitment/Index -> commitment failed
    E060_ROW_INDEX_COMMITMENT_MISSING: EXIT_COMMITMENT_FAILED,
    E061_ROW_INDEX_COMMITMENT_INVALID_FORMAT: EXIT_COMMITMENT_FAILED,
    E062_ROW_ARCHIVE_MISSING: EXIT_COMMITMENT_FAILED,
    E063_CHUNK_ROOTS_DIGEST_MISMATCH: EXIT_COMMITMENT_FAILED,
    E064_MERKLE_PROOF_INVALID: EXIT_COMMITMENT_FAILED,
    E065_CHUNK_ROOT_MISMATCH: EXIT_COMMITMENT_FAILED,
    E066_CHUNK_LENGTH_INVALID: EXIT_COMMITMENT_FAILED,
    E075_CHUNK_HANDLE_INVALID: EXIT_COMMITMENT_FAILED,
    E076_CHUNK_CARDINALITY_MISMATCH: EXIT_COMMITMENT_FAILED,

    # DA Audit -> DA audit failed
    E070_DA_MODE_UNSUPPORTED: EXIT_DA_AUDIT_FAILED,
    E071_DA_CHALLENGE_MISSING: EXIT_DA_AUDIT_FAILED,
    E072_DA_CHALLENGE_HASH_MISMATCH: EXIT_DA_AUDIT_FAILED,
    E073_DA_CHALLENGE_UNTRUSTED: EXIT_DA_AUDIT_FAILED,
    E074_AVAILABILITY_FAILED: EXIT_DA_AUDIT_FAILED,

    # Policy Enforcement -> policy mismatch
    E101_POLICY_VIOLATION_FORBID_GPU: EXIT_POLICY_MISMATCH,
    E102_POLICY_MISSING_PUBLIC_OUTPUT: EXIT_POLICY_MISMATCH,
    E103_POLICY_TRACK_UNKNOWN: EXIT_POLICY_MISMATCH,
    E104_POLICY_MANIFEST_MISSING: EXIT_POLICY_MISMATCH,
    E105_POLICY_DOCKER_DIGEST_MISSING: EXIT_POLICY_MISMATCH,
    E106_MANIFEST_SIGNATURE_MISSING: EXIT_POLICY_MISMATCH,
    E107_MANIFEST_SIGNATURE_INVALID: EXIT_POLICY_MISMATCH,
    E108_MANIFEST_SIGNER_UNTRUSTED: EXIT_POLICY_MISMATCH,
    E109_MANIFEST_REGISTRY_MISMATCH: EXIT_POLICY_MISMATCH,

    # Event log -> commitment failed
    E201_EVENT_LOG_MISMATCH: EXIT_COMMITMENT_FAILED,

    # Proof system -> proof invalid
    E301_PROOF_SYSTEM_MISMATCH: EXIT_PROOF_INVALID,
    E302_VERIFICATION_PROFILE_UNSATISFIED: EXIT_PROOF_INVALID,
}


def error_to_exit_code(error_code: str) -> int:
    """Map a verifier error code to an exit code."""
    return _ERROR_TO_EXIT.get(error_code, EXIT_MALFORMED)


def exit_code_description(code: int) -> str:
    """Return a human-readable description of an exit code."""
    descriptions = {
        EXIT_VERIFIED: "verified",
        EXIT_PROOF_INVALID: "proof invalid",
        EXIT_POLICY_MISMATCH: "policy mismatch",
        EXIT_COMMITMENT_FAILED: "commitment/index verification failed",
        EXIT_DA_AUDIT_FAILED: "DA audit failed",
        EXIT_REPLAY_DIVERGED: "replay diverged",
        EXIT_MALFORMED: "malformed or parse error",
    }
    return descriptions.get(code, "unknown error")
